default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myapp_development
  username: postgres
  password:

test:
  <<: *default
  database: myapp_test
  username: postgres
  password:

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

cable:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

cache:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
